#### 继承nn.Module类

In [1]:
from torch import nn

In [2]:
class Model(nn.Module):
    def __init__(self):
        super(Model,self).__init__()

    def forward(self,input):
        output = input+1
        return output

In [3]:
model = Model()

In [4]:
import torch

In [5]:
x = torch.tensor(1.0)
x

tensor(1.)

In [6]:
outout = model(x)
outout

tensor(2.)

#### 卷积

In [7]:
import torch

In [8]:
input = torch.tensor([[1,2,0,3,1],
                      [0,1,2,3,1],
                      [1,2,1,0,0],
                      [5,2,3,1,1],
                      [2,1,0,1,1]
                     ])
input

tensor([[1, 2, 0, 3, 1],
        [0, 1, 2, 3, 1],
        [1, 2, 1, 0, 0],
        [5, 2, 3, 1, 1],
        [2, 1, 0, 1, 1]])

In [9]:
kernel = torch.tensor([[1,2,1],
                       [0,1,0],
                       [2,1,0]
                      ])
kernel

tensor([[1, 2, 1],
        [0, 1, 0],
        [2, 1, 0]])

In [10]:
input.shape

torch.Size([5, 5])

In [11]:
kernel.shape

torch.Size([3, 3])

**变换尺寸**

In [12]:
input = torch.reshape(input,(1,1,5,5))

input

tensor([[[[1, 2, 0, 3, 1],
          [0, 1, 2, 3, 1],
          [1, 2, 1, 0, 0],
          [5, 2, 3, 1, 1],
          [2, 1, 0, 1, 1]]]])

In [13]:
kernel = torch.reshape(kernel,(1,1,3,3))
kernel

tensor([[[[1, 2, 1],
          [0, 1, 0],
          [2, 1, 0]]]])

In [14]:
import torch.nn.functional as F

**卷积结果**

In [15]:
output = F.conv2d(input,kernel,stride=1) # 步长为1
output 

tensor([[[[10, 12, 12],
          [18, 16, 16],
          [13,  9,  3]]]])

In [16]:
output2 = F.conv2d(input,kernel,stride=2) # 步长为2
output2

tensor([[[[10, 12],
          [13,  3]]]])

In [17]:
output3 = F.conv2d(input,kernel,stride=1,padding=1) # 步长为1 # 周围填充一个像素 默认填充0
output3

tensor([[[[ 1,  3,  4, 10,  8],
          [ 5, 10, 12, 12,  6],
          [ 7, 18, 16, 16,  8],
          [11, 13,  9,  3,  4],
          [14, 13,  9,  7,  4]]]])

#### 卷积层

In [18]:
import torch
import torchvision
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter

In [19]:
dataset = torchvision.datasets.CIFAR10(
    root = "../../../datas",
    train = False,
    download = True,
    transform = torchvision.transforms.ToTensor()
)

Files already downloaded and verified


In [20]:
dataloader = DataLoader(dataset,batch_size=64)

In [21]:
from torch.nn import Conv2d
class Model(torch.nn.Module):
    def __init__(self):
        super(Model,self).__init__()
        self.conv1 = Conv2d(in_channels=3,out_channels=6,kernel_size=3,stride=1,padding=0)   # 第一层卷积
        
    def forward(self,x):
        x = self.conv1(x)
        return x

In [22]:
model = Model()
model

Model(
  (conv1): Conv2d(3, 6, kernel_size=(3, 3), stride=(1, 1))
)

In [23]:
# writer = SummaryWriter("./卷积层_logs")
step = 1
for data in dataloader:
    imgs,targets = data
    output = model(imgs)
    print("卷积前：",imgs.shape)
    print("卷积后：",output.shape)
    
    output = torch.reshape(output,(-1,3,30,30))
    
    # writer.add_images("input",imgs,step)
    # writer.add_images("output",output,step)
    step+=1
    


卷积前： torch.Size([64, 3, 32, 32])
卷积后： torch.Size([64, 6, 30, 30])
卷积前： torch.Size([64, 3, 32, 32])
卷积后： torch.Size([64, 6, 30, 30])
卷积前： torch.Size([64, 3, 32, 32])
卷积后： torch.Size([64, 6, 30, 30])
卷积前： torch.Size([64, 3, 32, 32])
卷积后： torch.Size([64, 6, 30, 30])
卷积前： torch.Size([64, 3, 32, 32])
卷积后： torch.Size([64, 6, 30, 30])
卷积前： torch.Size([64, 3, 32, 32])
卷积后： torch.Size([64, 6, 30, 30])
卷积前： torch.Size([64, 3, 32, 32])
卷积后： torch.Size([64, 6, 30, 30])
卷积前： torch.Size([64, 3, 32, 32])
卷积后： torch.Size([64, 6, 30, 30])
卷积前： torch.Size([64, 3, 32, 32])
卷积后： torch.Size([64, 6, 30, 30])
卷积前： torch.Size([64, 3, 32, 32])
卷积后： torch.Size([64, 6, 30, 30])
卷积前： torch.Size([64, 3, 32, 32])
卷积后： torch.Size([64, 6, 30, 30])
卷积前： torch.Size([64, 3, 32, 32])
卷积后： torch.Size([64, 6, 30, 30])
卷积前： torch.Size([64, 3, 32, 32])
卷积后： torch.Size([64, 6, 30, 30])
卷积前： torch.Size([64, 3, 32, 32])
卷积后： torch.Size([64, 6, 30, 30])
卷积前： torch.Size([64, 3, 32, 32])
卷积后： torch.Size([64, 6, 30, 30])
卷积前： torch