### 损失函数

In [1]:
import torch
import torch.nn as nn

In [2]:
input = torch.tensor([1,2,3],dtype=torch.float32)
target = torch.tensor([1,2,5],dtype=torch.float32)

In [3]:
input

tensor([1., 2., 3.])

In [4]:
target

tensor([1., 2., 5.])

In [5]:
input = torch.reshape(input,(1,1,1,3))
target = torch.reshape(target,(1,1,1,3))

In [6]:
input

tensor([[[[1., 2., 3.]]]])

In [7]:
target

tensor([[[[1., 2., 5.]]]])

#### 1. L1Loss  

In [8]:
loss = nn.L1Loss()  # 设置reduction = 'sum' 就是求和，不求均值
result = loss(input,target)

In [9]:
result

tensor(0.6667)

#### 2. MSELoss 

In [10]:
loss_mse = nn.MSELoss()
result_mse = loss_mse(input,target) 

In [11]:
result_mse

tensor(1.3333)

#### 3. CROSSENTROPYLoss

In [12]:
x = torch.tensor([0.1,0.2,0.3])
y = torch.tensor([1])

In [13]:
x = torch.reshape(x,(1,3)) # 有三类
x

tensor([[0.1000, 0.2000, 0.3000]])

In [14]:
loss_cross = nn.CrossEntropyLoss()

In [15]:
result_Cross = loss_cross(x,y)
result_Cross

tensor(1.1019)

#### 损失函数实操 

In [16]:
class Model2(nn.Module):
    def __init__(self):
        super(Model2,self).__init__()
        self.model = nn.Sequential(
            nn.Conv2d(3,32,5,padding=2),
            nn.MaxPool2d(2),
            nn.Conv2d(32,32,5,padding=2),
            nn.MaxPool2d(2),
            nn.Conv2d(32,64,5,padding=2),
            nn.MaxPool2d(2),
            nn.Flatten(),
            nn.Linear(1024,64),
            nn.Linear(64,10)
        )
    
    def forward(self,x):
        x = self.model(x)
        return x

In [17]:
import torchvision
from torch.utils.data import DataLoader

In [18]:
dataset = torchvision.datasets.CIFAR10(
    root = "../../../datas",
    train = False,
    download = True,
    transform = torchvision.transforms.ToTensor()
)

Files already downloaded and verified


In [19]:
dataloader = DataLoader(dataset,batch_size=1)

In [20]:
model = Model2()

In [21]:
for data in dataloader:
    imgs,targets = data
    outputs = model(imgs)
    print(outputs)
    print(targets)
    result_loss = loss(outputs,targets)
    print(result_loss) #实际输出与目标之间的误差
    break

tensor([[ 0.0611,  0.0791, -0.1297, -0.0609,  0.0452,  0.0773,  0.1266, -0.0355,
          0.0939, -0.0932]], grad_fn=<AddmmBackward0>)
tensor([3])
tensor(2.9836, grad_fn=<L1LossBackward0>)


e:\python\envs\AI\lib\site-packages\torch\nn\modules\loss.py:96: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 10])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)


### 优化器与反向传播 

In [22]:
# 设置优化器
optim = torch.optim.SGD(model.parameters(),lr=0.01) # lr:学习速率

# 设置损失函数
loss = torch.nn.CrossEntropyLoss()

In [23]:
for epoch in range(20):        # 20轮学习
    running_loss = 0.0
    for data in dataloader:
        imgs,targets = data
        outputs = model(imgs)
        result_loss = loss(outputs,targets)
        optim.zero_grad()      # 归零设置
        result_loss.backward() # 计算参数结点梯度，反向传播
        optim.step()           # 对模型参数调优
        running_loss = running_loss + result_loss
    print(running_loss)

tensor(18796.0430, grad_fn=<AddBackward0>)
tensor(16230.1553, grad_fn=<AddBackward0>)
tensor(15363.7725, grad_fn=<AddBackward0>)
tensor(16050.4121, grad_fn=<AddBackward0>)
tensor(17864.2715, grad_fn=<AddBackward0>)
tensor(20308.3359, grad_fn=<AddBackward0>)
tensor(22124.3125, grad_fn=<AddBackward0>)
tensor(23408.3730, grad_fn=<AddBackward0>)
tensor(24673.9941, grad_fn=<AddBackward0>)
tensor(24994.8008, grad_fn=<AddBackward0>)
tensor(25338.1953, grad_fn=<AddBackward0>)
tensor(25939.2402, grad_fn=<AddBackward0>)
tensor(26191.7969, grad_fn=<AddBackward0>)
tensor(26935.6152, grad_fn=<AddBackward0>)
tensor(28035.4785, grad_fn=<AddBackward0>)
tensor(28942.5391, grad_fn=<AddBackward0>)
tensor(31423.3457, grad_fn=<AddBackward0>)
tensor(nan, grad_fn=<AddBackward0>)
tensor(nan, grad_fn=<AddBackward0>)
tensor(nan, grad_fn=<AddBackward0>)
