In [4]:
import torch

求导,设置记录梯度

In [5]:
#方法一：
x=torch.randn(3,4,requires_grad=True)
x

tensor([[ 0.7217,  1.4533, -0.7615, -1.3646],
        [ 0.3827,  0.0043, -0.0174, -0.2611],
        [ 0.1874, -1.6020, -0.5046, -0.4364]], requires_grad=True)

In [6]:
#方法二：
x=torch.randn(3,4)
x.requires_grad=True
x

tensor([[-0.0374,  0.6347,  0.1854, -1.1142],
        [-1.0141, -1.3663, -0.5125,  0.2629],
        [-0.2457, -0.2553,  1.0669, -0.5322]], requires_grad=True)

### 小demo

In [83]:
b=torch.randn(3,4,requires_grad=True)
t=x+b
#.sum()所有元素求和
y=t.sum()
y

tensor(-4.1989, grad_fn=<SumBackward0>)

In [84]:
y.backward()
b.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [85]:
x.requires_grad,y.requires_grad,t.requires_grad

(False, True, True)

In [86]:
x=torch.rand(1)
b=torch.rand(1,requires_grad=True)
w=torch.rand(1,requires_grad=True)
y=w*x
z=y+b

In [87]:
x.requires_grad,b.requires_grad,y.requires_grad,z.requires_grad

(False, True, True, True)

查看是不是叶子

In [88]:
x.is_leaf,w.is_leaf,y.is_leaf,b.is_leaf,z.is_leaf

(True, True, False, True, False)

反向传播计算

In [89]:
#retain_graph==True后,会累加起来，如果为False则销毁结点，不能再backward
z.backward(retain_graph=True)

In [90]:
w.grad

tensor([0.8042])

In [91]:
b.grad

tensor([1.])