## Tensor常见的形式
* scalar
* vechor
* matrix
* n-dimensional tensor

In [1]:
import torch
from torch import tensor

## Scalar
通常是一个数值

In [9]:
x=tensor(42.)
x

tensor(42.)

*.dim()获取维度*

In [10]:
x.dim()

0

In [11]:
2*x

tensor(84.)

*pytorch中，.item()方法 是得到一个元素张量里面的元素值  
具体就是 用于将一个零维张量转换成浮点数，比如计算loss，accuracy的值*

In [12]:
x.item()

42.0

## Vector
例如：[-5.,2.,0.]，在深度学习中通常是指特征，例如词向量特征，某一维度特征等

In [13]:
v=tensor([1.4,-0.5,3.0])
v

tensor([ 1.4000, -0.5000,  3.0000])

In [14]:
v.dim()

1

*.size()获取每个维度数量*

In [20]:
v.size()

torch.Size([3])

## Matrix
* 一般计算的都是矩阵，通常都是多维的

In [21]:
M=tensor([[1.,2.],[3.,4.]])
M

tensor([[1., 2.],
        [3., 4.]])

*.matmul()矩阵乘法*

In [22]:
M.matmul(M)

tensor([[ 7., 10.],
        [15., 22.]])

In [23]:
M*M

tensor([[ 1.,  4.],
        [ 9., 16.]])

## n-dimensional tensor
多维矩阵