查看Pytorch版本

In [3]:
import torch
torch.__version__

'1.10.0'

创建一个矩阵

In [22]:
x=torch.empty(5,3)
x

tensor([[9.2755e-39, 8.4490e-39, 8.9082e-39],
        [9.1837e-39, 1.0561e-38, 9.0918e-39],
        [1.0469e-38, 8.4490e-39, 1.0469e-38],
        [8.9082e-39, 1.0561e-38, 1.0561e-38],
        [8.9082e-39, 1.0561e-38, 8.4490e-39]])

随机值

In [25]:
x=torch.rand(5,3)
x

tensor([[0.1257, 0.0366, 0.6893],
        [0.4640, 0.9283, 0.8454],
        [0.7797, 0.0531, 0.0716],
        [0.3599, 0.8169, 0.7366],
        [0.8598, 0.3150, 0.3625]])

初始化全零矩阵

In [29]:
x=torch.zeros(5,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

展示矩阵大小

In [31]:
x.size()

torch.Size([5, 3])

## 基本计算方法

In [35]:
y=torch.rand(5,3)
print(x)
print(y)
print(x+y)
torch.add(x,y)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.0646, 0.9645, 0.3827],
        [0.7828, 0.5056, 0.0586],
        [0.4464, 0.3433, 0.8438],
        [0.2937, 0.4613, 0.4555],
        [0.6152, 0.0818, 0.7641]])
tensor([[0.0646, 0.9645, 0.3827],
        [0.7828, 0.5056, 0.0586],
        [0.4464, 0.3433, 0.8438],
        [0.2937, 0.4613, 0.4555],
        [0.6152, 0.0818, 0.7641]])


tensor([[0.0646, 0.9645, 0.3827],
        [0.7828, 0.5056, 0.0586],
        [0.4464, 0.3433, 0.8438],
        [0.2937, 0.4613, 0.4555],
        [0.6152, 0.0818, 0.7641]])

索引

In [37]:
print(y)
y[:,1]

tensor([[0.0646, 0.9645, 0.3827],
        [0.7828, 0.5056, 0.0586],
        [0.4464, 0.3433, 0.8438],
        [0.2937, 0.4613, 0.4555],
        [0.6152, 0.0818, 0.7641]])


tensor([0.9645, 0.5056, 0.3433, 0.4613, 0.0818])

### view操作改变举证维度

In [43]:
#randn随机抽取0~1符合正态分布
x=torch.randn(4,4)
print(x)
y=x.view(16)
print(y)
#-1表示自动计算
z=x.view(-1,8)
print(z)
z.size()

tensor([[ 0.0548,  0.1954, -0.1048, -0.0717],
        [-2.1984, -0.5006,  0.3224,  1.4273],
        [ 2.3016,  0.2484,  0.0952,  0.0919],
        [ 1.1520,  0.7749, -1.2090,  0.9059]])
tensor([ 0.0548,  0.1954, -0.1048, -0.0717, -2.1984, -0.5006,  0.3224,  1.4273,
         2.3016,  0.2484,  0.0952,  0.0919,  1.1520,  0.7749, -1.2090,  0.9059])
tensor([[ 0.0548,  0.1954, -0.1048, -0.0717, -2.1984, -0.5006,  0.3224,  1.4273],
        [ 2.3016,  0.2484,  0.0952,  0.0919,  1.1520,  0.7749, -1.2090,  0.9059]])


torch.Size([2, 8])

## 与Numpy协同

In [47]:
a=torch.ones(5)
print(a)
b=a.numpy()
b

tensor([1., 1., 1., 1., 1.])


array([1., 1., 1., 1., 1.], dtype=float32)

In [49]:
import numpy
a=numpy.ones(5)
print(a)
a=torch.from_numpy(a)
a

[1. 1. 1. 1. 1.]


tensor([1., 1., 1., 1., 1.], dtype=torch.float64)