# 线性回归模型

构造一组输入数据X和其对应的标签y

In [13]:
import numpy

numpy里面**reshape**使用

`np.arange(16).reshape(2,8) #生成16个自然数，以2行8列的形式显示
#Out: # array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])`

In [24]:

x_values=[i for i in range(11)]
print(x_values)
x_train=numpy.array(x_values,dtype=numpy.float32)
print(x_train)
print(x_train.shape)
x_train=x_train.reshape(-1,1)
print(x_train)
x_train.shape

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
(11,)
[[ 0.]
 [ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]


(11, 1)

In [26]:

y_values=[2*i+1 for i in x_values]
print(y_values)
y_train=numpy.array(y_values,dtype=numpy.float32)
print(y_train)
print(y_train.shape)
y_train=y_train.reshape(-1,1)
print(y_train)
y_train.shape

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21]
[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21.]
(11,)
[[ 1.]
 [ 3.]
 [ 5.]
 [ 7.]
 [ 9.]
 [11.]
 [13.]
 [15.]
 [17.]
 [19.]
 [21.]]


(11, 1)

In [15]:
import torch
import torch.nn as nn

## 线性回归模型
*子类定义了构造函数父类的构造函数不会调用，如果要调用父类构造函数  需要使用super的方法调用
*
* 线性回归是一个不加激活函数的全连接层

In [48]:
class LinearRegressionMode(nn.Module):
    def __init__(self,input_dim,output_dim):
        super(LinearRegressionMode,self).__init__()
        self.linear=nn.Linear(input_dim,output_dim)
    def forward(self,x):
        out=self.linear(x)
        return out

In [49]:
input_dim=1
output_dim=1
model=LinearRegressionMode(input_dim,output_dim)
model

LinearRegressionMode(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

learning rate
学习率较小时，收敛到极值的速度较慢。
学习率较大时，容易在搜索过程中发生震荡。

In [50]:
#训练次数
epochs=1000
learning_rate=0.01
optimizer =torch.optim.SGD(model.parameters(),lr=learning_rate)
criterion=nn.MSELoss()

训练模型

In [51]:
for epoch in range(epochs):
    epoch +=1
    #将数据转化为tensor格式
    inputs=torch.from_numpy(x_train)
    labels=torch.from_numpy(y_train)
    
    #梯度需要清零每一次迭代 否则会累加
    optimizer.zero_grad()
    
    #向前传播
    outputs=model(inputs)
    
    #计算损失
    loss=criterion(outputs,labels)
    
    #反向传播
    loss.backward()
    
    #更新权重参数
    optimizer.step()
    if epoch%50==0:
        print("epoch{},loss{}".format(epoch,loss.item()))
    

epoch50,loss0.24509991705417633
epoch100,loss0.13979583978652954
epoch150,loss0.07973436266183853
epoch200,loss0.04547741636633873
epoch250,loss0.02593870274722576
epoch300,loss0.014794432558119297
epoch350,loss0.008438210934400558
epoch400,loss0.004812836181372404
epoch450,loss0.0027450702618807554
epoch500,loss0.001565694808959961
epoch550,loss0.0008930069743655622
epoch600,loss0.0005093320505693555
epoch650,loss0.0002905012806877494
epoch700,loss0.0001656898675719276
epoch750,loss9.450827928958461e-05
epoch800,loss5.39022839802783e-05
epoch850,loss3.074334017583169e-05
epoch900,loss1.7534242942929268e-05
epoch950,loss9.999141184380278e-06
epoch1000,loss5.704422164853895e-06


## 模型的保存与读取

In [56]:
#保存
torch.save(model.state_dict(),'model.pkl')

In [59]:
#读取
model.load_state_dict(torch.load('model.pkl'))

<All keys matched successfully>

### 使用GPU训练
* 把数据与模型传到cuda里面

In [62]:
# 1.模型传入
device=torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
#print(device)
model.to(device)
# 2.数据传入
inputs=torch.from_numpy(x_train).to(device)
labels=torch.from_numpy(y_train).to(device)