查看Pytorch版本

In [1]:
import torch
torch.__version__

'1.12.1+cu113'

创建一个矩阵

In [2]:
x=torch.empty(5,3)
x

tensor([[-3.6899e-18,  5.0867e-43, -3.6899e-18],
        [ 5.0867e-43, -3.6899e-18,  5.0867e-43],
        [-3.6899e-18,  5.0867e-43, -3.6899e-18],
        [ 5.0867e-43, -3.6899e-18,  5.0867e-43],
        [-3.6899e-18,  5.0867e-43, -3.6899e-18]])

创建随机矩阵

In [3]:
x=torch.rand(5,3)
x

tensor([[0.2921, 0.7177, 0.8859],
        [0.0557, 0.2752, 0.4578],
        [0.1084, 0.2498, 0.2182],
        [0.1561, 0.9114, 0.7252],
        [0.0864, 0.0049, 0.4055]])

创建全零矩阵

In [4]:
x=torch.zeros(5,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

直接创建矩阵

In [5]:
torch.tensor([5.5,6])

tensor([5.5000, 6.0000])

展示矩阵大小

In [6]:
x.shape

torch.Size([5, 3])

In [7]:
x.size()

torch.Size([5, 3])

基本计算方法

In [8]:
y=torch.rand(5,3)
print(x)
print(y)
print(x+y)
torch.add(x,y)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.9980, 0.3633, 0.3511],
        [0.2977, 0.7337, 0.3576],
        [0.3951, 0.2728, 0.6807],
        [0.9268, 0.4716, 0.8123],
        [0.1069, 0.2722, 0.7626]])
tensor([[0.9980, 0.3633, 0.3511],
        [0.2977, 0.7337, 0.3576],
        [0.3951, 0.2728, 0.6807],
        [0.9268, 0.4716, 0.8123],
        [0.1069, 0.2722, 0.7626]])


tensor([[0.9980, 0.3633, 0.3511],
        [0.2977, 0.7337, 0.3576],
        [0.3951, 0.2728, 0.6807],
        [0.9268, 0.4716, 0.8123],
        [0.1069, 0.2722, 0.7626]])

索引

In [9]:
print(y)
y[:,1]

tensor([[0.9980, 0.3633, 0.3511],
        [0.2977, 0.7337, 0.3576],
        [0.3951, 0.2728, 0.6807],
        [0.9268, 0.4716, 0.8123],
        [0.1069, 0.2722, 0.7626]])


tensor([0.3633, 0.7337, 0.2728, 0.4716, 0.2722])

view操作改变举证维度

In [10]:
#randn随机抽取0~1符合正态分布
x=torch.randn(4,4)
print(x)
y=x.view(16)
print(y)
#-1表示自动计算
z=x.view(-1,8)
print(z)
z.size()

tensor([[-0.3466,  2.1478,  0.5054, -0.8719],
        [ 0.4411,  0.5535, -0.8940,  0.4281],
        [-0.2212, -0.4165, -0.1465,  0.7729],
        [-0.2295, -0.3552,  0.8396, -0.1295]])
tensor([-0.3466,  2.1478,  0.5054, -0.8719,  0.4411,  0.5535, -0.8940,  0.4281,
        -0.2212, -0.4165, -0.1465,  0.7729, -0.2295, -0.3552,  0.8396, -0.1295])
tensor([[-0.3466,  2.1478,  0.5054, -0.8719,  0.4411,  0.5535, -0.8940,  0.4281],
        [-0.2212, -0.4165, -0.1465,  0.7729, -0.2295, -0.3552,  0.8396, -0.1295]])


torch.Size([2, 8])

与Numpy协同

In [11]:
a=torch.ones(5)
print(a)
b=a.numpy()
b

tensor([1., 1., 1., 1., 1.])


array([1., 1., 1., 1., 1.], dtype=float32)

In [12]:
import numpy
a=numpy.ones(5)
print(a)
a=torch.from_numpy(a)
a

[1. 1. 1. 1. 1.]


tensor([1., 1., 1., 1., 1.], dtype=torch.float64)