In [18]:
import torch

求导,设置记录梯度

In [19]:
#方法一：
x=torch.randn(3,4,requires_grad=True)
x

tensor([[-1.4001, -0.7287,  0.7482,  0.5315],
        [-0.6022,  0.9874,  0.4093, -1.4547],
        [-0.3030,  0.8827, -0.0161,  0.3327]], requires_grad=True)

In [20]:
#方法二：
x=torch.randn(3,4)
x.requires_grad=True
x

tensor([[-0.9313,  1.1730,  0.2375,  1.4344],
        [-0.5414,  0.0356, -0.5664, -0.1289],
        [ 0.0110, -0.2295, -1.3376,  0.5138]], requires_grad=True)

求导

In [21]:
b=torch.randn(3,4,requires_grad=True)
t=x+b
#.sum()所有元素求和
y=t.sum()
y

tensor(6.1005, grad_fn=<SumBackward0>)

In [22]:
y.backward()
b.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
x.requires_grad,y.requires_grad,t.requires_grad

(True, True, True)

In [24]:
x=torch.rand(1)
b=torch.rand(1,requires_grad=True)
w=torch.rand(1,requires_grad=True)
y=w*x
z=y+b

In [25]:
x.requires_grad,b.requires_grad,y.requires_grad,z.requires_grad

(False, True, True, True)

查看是不是叶子

In [26]:
x.is_leaf,w.is_leaf,y.is_leaf,b.is_leaf,z.is_leaf

(True, True, False, True, False)

反向传播计算

In [27]:
#retain_graph==True后,会累加起来，如果为False则销毁结点，不能再backward
z.backward(retain_graph=True)

In [28]:
w.grad

tensor([0.9561])

In [29]:
b.grad

tensor([1.])

梯度不清零会累加