In [1]:
from sklearn.datasets import load_iris

In [5]:
iris = load_iris()
iris_data = iris["data"]
iris_target = iris["target"]
print(iris_data[30:40])
print(iris_target[30:40])
print(len(iris_data))
print(type(iris_target))
print(iris_target.dtype)

[[4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]]
[0 0 0 0 0 0 0 0 0 0]
150
<class 'numpy.ndarray'>
int32


In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test = train_test_split(iris.data,test_size=0.2,random_state=8)
print(len(x_test))
print(x_train)

30
[[5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.1]
 [4.6 3.6 1.  0.2]
 [6.7 3.3 5.7 2.1]
 [5.5 2.6 4.4 1.2]
 [6.8 2.8 4.8 1.4]
 [6.1 2.6 5.6 1.4]
 [5.6 3.  4.1 1.3]
 [5.5 4.2 1.4 0.2]
 [5.7 2.9 4.2 1.3]
 [5.6 2.5 3.9 1.1]
 [4.5 2.3 1.3 0.3]
 [6.  2.9 4.5 1.5]
 [6.6 2.9 4.6 1.3]
 [5.9 3.  5.1 1.8]
 [5.  3.3 1.4 0.2]
 [5.  3.5 1.6 0.6]
 [5.  3.5 1.3 0.3]
 [6.9 3.1 5.4 2.1]
 [6.4 2.7 5.3 1.9]
 [5.7 2.5 5.  2. ]
 [7.9 3.8 6.4 2. ]
 [5.  3.  1.6 0.2]
 [4.4 2.9 1.4 0.2]
 [6.  2.2 4.  1. ]
 [5.5 2.4 3.8 1.1]
 [4.9 2.4 3.3 1. ]
 [4.8 3.4 1.6 0.2]
 [5.  3.2 1.2 0.2]
 [6.7 3.  5.  1.7]
 [6.3 3.3 6.  2.5]
 [5.4 3.9 1.7 0.4]
 [5.7 2.8 4.1 1.3]
 [6.  3.  4.8 1.8]
 [5.7 2.6 3.5 1. ]
 [4.8 3.4 1.9 0.2]
 [6.7 3.3 5.7 2.5]
 [6.3 2.3 4.4 1.3]
 [5.7 2.8 4.5 1.3]
 [5.4 3.9 1.3 0.4]
 [6.6 3.  4.4 1.4]
 [6.8 3.2 5.9 2.3]
 [7.7 2.8 6.7 2. ]
 [5.1 3.8 1.5 0.3]
 [5.6 2.8 4.9 2. ]
 [6.5 3.  5.5 1.8]
 [5.6 2.7 4.2 1.3]
 [6.1 2.8 4.7 1.2]
 [5.2 4.1 1.5 0.1]
 [4.6 3.4 1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [5.1 3.4 1.5 0.2]
 [6.5 2.8

In [24]:
from sklearn.feature_extraction import DictVectorizer
transer = DictVectorizer(sparse=False)
data = [{"city":"北京","temperature":41},{"city":"武汉","temperature":32},{"city":"重庆","temperature":38}]
data_new = transer.fit_transform(data)
print(data_new)
print("特征名字：\n",transer.get_feature_names())

[[ 1.  0.  0. 41.]
 [ 0.  1.  0. 32.]
 [ 0.  0.  1. 38.]]
特征名字：
 ['city=北京', 'city=武汉', 'city=重庆', 'temperature']


In [25]:
from sklearn.feature_extraction.text import CountVectorizer
data = ["life is short,i like python,python is easy","i want do it","i can do it","我爱中国,我爱 python"]
# 1. 创建实例化对象
transer = CountVectorizer()  # 参数 stop_words=["is","do"]
# 2. 调用fit_tranform()
data_new = transer.fit_transform(data)

print("特征名字：\n",transer.get_feature_names())
print("转换后数据：\n",data_new.toarray())

特征名字：
 ['can', 'do', 'easy', 'is', 'it', 'life', 'like', 'python', 'short', 'want', '我爱', '我爱中国']
转换后数据：
 [[0 0 1 2 0 1 1 2 1 0 0 0]
 [0 1 0 0 1 0 0 0 0 1 0 0]
 [1 1 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 1 1]]


e:\python\anaconda\envs\AI\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [29]:
import jieba
text = ["见扫能吃辣说出口洒出","武器卡安吃撒你哦","哦啊市场开始","屏幕上查看"]

for i in text:
    split_word = " ".join(jieba.cut(i))
    print(split_word)

见 扫能 吃 辣 说 出口 洒出
武器 卡安吃 撒 你 哦
哦 啊 市场 开始
屏幕 上 查看


In [32]:
# 1. 获取数据
import pandas as pd
data = pd.read_csv("../../../datas/data.txt")
data = data.iloc[: , :3] # 取前三列
    
# 2. 实例化类
from sklearn.preprocessing import MinMaxScaler
transer = MinMaxScaler()    # 参数feature_range=[2,3] 默认0,1

# 3。 调用fit_transform
data_new = transer.fit_transform(data)
print(data)
print(data_new)

   milage    liters  consumtime
0   12412  8.215278     0.12754
1   12212  4.215742     0.18324
2   13812  5.212328     0.14124
3   62412  4.212428     0.25124
4   12412  2.215278     0.12324
5   52412  2.245278     0.23124
6   42212  7.225278     0.13234
[[0.00398406 1.         0.03359375]
 [0.         0.33341067 0.46875   ]
 [0.03187251 0.49950833 0.140625  ]
 [1.         0.33285833 1.        ]
 [0.00398406 0.         0.        ]
 [0.80079681 0.005      0.84375   ]
 [0.59760956 0.835      0.07109375]]


In [46]:
import pandas as pd
data = pd.read_csv("../../../datas/factor_returns.csv")
data = data.iloc[:,1:-2]

# 2. 实例化类
from sklearn.feature_selection import VarianceThreshold
transer = VarianceThreshold(threshold=20)  # threshold=5 默认为0
# 3。 调用fit_transform
data_new = transer.fit_transform(data)
print(data.columns)
print(data_new)
print(data.shape)
print(data_new.shape)
# 计算两个变量相关系数
from scipy.stats import pearsonr
r = pearsonr(data["pe_ratio"],data["pb_ratio"])
print(r)

Index(['pe_ratio', 'pb_ratio', 'market_cap', 'return_on_asset_net_profit',
       'du_return_on_equity', 'ev', 'earnings_per_share', 'revenue',
       'total_expense'],
      dtype='object')
[[ 5.95720000e+00  8.52525509e+10  8.00800000e-01 ...  1.21144486e+12
   2.07014010e+10  1.08825400e+10]
 [ 7.02890000e+00  8.41133582e+10  1.64630000e+00 ...  3.00252062e+11
   2.93083692e+10  2.37834769e+10]
 [-2.62746100e+02  5.17045520e+08 -5.67800000e-01 ...  7.70517753e+08
   1.16798290e+07  1.20300800e+07]
 ...
 [ 3.95523000e+01  1.70243430e+10  3.34400000e+00 ...  2.42081699e+10
   1.78908166e+10  1.74929478e+10]
 [ 5.25408000e+01  3.28790988e+10  2.74440000e+00 ...  3.88380258e+10
   6.46539204e+09  6.00900728e+09]
 [ 1.42203000e+01  5.91108572e+10  2.03830000e+00 ...  2.02066110e+11
   4.50987171e+10  4.13284212e+10]]
(2318, 9)
(2318, 7)
(-0.0043893227799362885, 0.8327205496564927)


In [48]:
# 1. 获取数据
from sklearn.datasets import load_iris
iris = load_iris()
# 2. 划分数据集
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target,random_state= 8)
# 3. 特征工程 ： 标准化
from sklearn.preprocessing import StandardScaler
transer = StandardScaler()
x_train = transer.fit_transform(x_train)
x_test = transer.fit_transform(x_test)
# 4. KNN算法预估器
from sklearn.neighbors import KNeighborsClassifier
estimator = KNeighborsClassifier(n_neighbors=9)
estimator.fit(x_train,y_train)

# 5. 模型评估
 # 法一 直接比对真实值和预测值
y_predict =  estimator.predict(x_test)
print("y_predict:\n",y_predict)
print("直接比对真实值和预测值：\n",y_predict == y_test)
    
# 法二 计算准确率
score = estimator.score(x_test,y_test)
print("准确率：\n",score)

y_predict:
 [0 0 0 2 1 0 0 2 2 1 1 0 1 1 1 2 2 2 1 2 1 0 1 1 1 0 2 0 0 2 0 0 0 2 1 1 2
 1]
直接比对真实值和预测值：
 [ True  True  True  True  True  True  True  True  True  True  True  True
 False  True False  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True]
准确率：
 0.9473684210526315


## 用已有数据来对生医杯数据做个分类
三分类(睁眼，闭眼，睡眠)