## 1 向量

### 1.1 向量描述方法 

**numpy中用数组表示向量**
1. 行向量

In [1]:
import numpy as np
u = np.array([1,6,7])
u

array([1, 6, 7])

2. 列向量

In [4]:
v = u.reshape(-1,1)
v

array([[1],
       [6],
       [7]])

3. 运算速度示例

In [9]:
import random,time
# 创建列表
lst = [random.randint(1,100) for i in range(1000000)]

start = time.time()
lst = [i*i for i in lst]  # 列表形式计算平方
end = time.time()
print(f"用时：{end - start}s")

vlst = np.array(lst)      # 列表化为数组
start2 = time.time()
vlst2 = vlst*vlst         # 用数组计算平方
end2 = time.time();
print(f"用时：{end2 - start2}s")

print(f"数组用时快{round((end - start)/(end2 - start2),3)}倍")

用时：0.1150047779083252s
用时：0.003022909164428711s
数组用时快38.044倍


###  1..2 向量加法

* 数组相加 

In [11]:
np.array([[2],[1]]) + np.array([[3],[3]])

array([[5],
       [4]])

* 数组相减

In [12]:
np.array([[2],[1]]) - np.array([[3],[3]])

array([[-1],
       [-2]])

### 1.3 向量的数量乘法 

* 标量乘以数组

In [14]:
2 * np.array([3,1])

array([6, 2])

In [15]:
-1 * np.array([3,1])

array([-3, -1])

## 2. 向量空间 

### 2.1 什么是向量空间 

* 两个向量相加所得到的向量，依然在这个二维平面空间中； 
* 经过数量乘法所得到的向量，也在这个二维平面空间中。

### 2.2 向量叉积 

叉积（Cross Product），又称矢量积（Vector Product）